// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (9090);

service / on ep0 {

    public function init() {
        log:printInfo("Pre Issue Access Token Action E2E Service started.");
    }

    # handle pre-issue access token events
    #
    # + payload - parameter description 
    # + return - returns can be any of following types
    # OkInline_response_200 (Ok)
    # BadRequestErrorResponse (Bad Request)
    # InternalServerErrorErrorResponse (Server Error)
    resource function post preIssueAccessTokenUpdateScopes(@http:Payload RequestBody payload) returns OkInline_response_200|BadRequestErrorResponse|InternalServerErrorErrorResponse {

        log:printInfo("Request Received to Update Scopes of the access token");
        log:printInfo(payload.toString());

        string grantType = payload.event.request.grantType;
        SuccessResponse respBody;
        if (grantType == "refresh_token") {
            respBody = {
                "actionStatus": "SUCCESS",
                "operations": [
                    {
                        op: "remove",
                        path: "/accessToken/scopes/0"
                    }
                ]
            };
        } else {
            respBody = {
                "actionStatus": "SUCCESS",
                "operations": [
                    {
                        op: "add",
                        path: "/accessToken/scopes/-",
                        value: "test_api_perm_3"
                    },
                    {
                        op: "add",
                        path: "/accessToken/scopes/0",
                        value: "test_api_perm_2"
                    },
                    {
                        op: "remove",
                        path: "/accessToken/scopes/0"
                    },
                    {
                        op: "replace",
                        path: "/accessToken/scopes/1",
                        value: "test_api_perm_1"
                    }
                ]
            };
        }
        OkInline_response_200 resp = {
            "body": respBody
        };
        log:printInfo("SUCCESS Response: " + resp.toString());
        return resp;
    }

    resource function post preIssueAccessTokenUpdateAudience(@http:Payload RequestBody payload) returns OkInline_response_200|BadRequestErrorResponse|InternalServerErrorErrorResponse {
        
        log:printInfo("Request Received to Update Scopes of the access token");
        log:printInfo(payload.toString());
        
        string grantType = payload.event.request.grantType;
        SuccessResponse respBody;
        if (grantType == "refresh_token") { 
            respBody = {
                "actionStatus": "SUCCESS",
                "operations": [
                    {
                        op: "remove",
                        path: "/accessToken/claims/aud/0"
                    }
                ]
            };
        } else {
            respBody = {
                "actionStatus": "SUCCESS",
                "operations": [
                    {
                        op: "add",
                        path: "/accessToken/claims/aud/-",
                        value: "https://myextension.com"
                    },
                    {
                        op: "remove",
                        path: "/accessToken/claims/aud/1"
                    },
                    {
                        op: "replace",
                        path: "/accessToken/claims/aud/0",
                        value: "https://localhost:8090"
                    }
                ]
            };
        }
        OkInline_response_200 resp = {
            "body": respBody
        };
        log:printInfo("SUCCESS Response: " + resp.toString());
        return resp;
    }

    resource function post preIssueAccessTokenUpdateOidcClaims(@http:Payload RequestBody payload) returns OkInline_response_200|BadRequestErrorResponse|InternalServerErrorErrorResponse {

        log:printInfo("Request Received to Update Scopes of the access token");
        log:printInfo(payload.toString());
        
        string grantType = payload.event.request.grantType;
        SuccessResponse respBody;
        if (grantType == "refresh_token") {
            respBody = {
                "actionStatus": "SUCCESS",
                "operations": [
                    {
                        op: "remove",
                        path: "/accessToken/claims/groups/0"
                    }
                ]
            };
        } else {
            respBody = {
                "actionStatus": "SUCCESS",
                "operations": [
                    {
                        op: "remove",
                        path: "/accessToken/claims/groups/0"
                    },
                    {
                        op: "replace",
                        path: "/accessToken/claims/groups/1",
                        value: "verifiedGroup1"
                    },
                    {
                        op: "replace",
                        path: "/accessToken/claims/username",
                        value: "US/JohnDoe"
                    }
                ]
            };
        }
        OkInline_response_200 resp = {
            "body": respBody
        };
        log:printInfo("SUCCESS Response: " + resp.toString());
        return resp;
    }

    resource function post preIssueAccessTokenUpdateTokenExpiryTime(@http:Payload RequestBody payload) returns OkInline_response_200|BadRequestErrorResponse|InternalServerErrorErrorResponse {
        
        log:printInfo("Request Received to Update Scopes of the access token");
        log:printInfo(payload.toString());
        
        string grantType = payload.event.request.grantType;
        SuccessResponse respBody;
        if (grantType == "refresh_token") {
            respBody = {
                "actionStatus": "SUCCESS",
                "operations": [
                    {
                        op: "replace",
                        path: "/accessToken/claims/expires_in",
                        value: "3000"
                    }
                ]
            };
        } else {
            respBody = {
                "actionStatus": "SUCCESS",
                "operations": [
                    {
                        op: "replace",
                        path: "/accessToken/claims/expires_in",
                        value: "4000"
                    }
                ]
            };
        }
        OkInline_response_200 resp = {
            "body": respBody
        };
        log:printInfo("SUCCESS Response: " + resp.toString());
        return resp;
    }

    resource function post preIssueAccessTokenAddCustomClaims(@http:Payload RequestBody payload) returns OkInline_response_200|BadRequestErrorResponse|InternalServerErrorErrorResponse {
        
        log:printInfo("Request Received to Update Scopes of the access token");
        log:printInfo(payload.toString());
        
        string grantType = payload.event.request.grantType;
        SuccessResponse respBody;
        if (grantType == "refresh_token") {
            string? prevGrantType = getAccessTokenClaim(payload, "grantType");
            if prevGrantType != null {
                respBody = {
                    "actionStatus": "SUCCESS",
                    "operations": [
                        {
                            op: "replace",
                            path: "/accessToken/claims/grantType",
                            value: grantType.toString()
                        },
                        {
                            op: "add",
                            path: "/accessToken/claims/-",
                            value: {
                                name: "previousGrantType",
                                value: prevGrantType
                            }
                        }
                    ]
                };
            } else {
                respBody = {
                    "actionStatus": "SUCCESS",
                    "operations": [
                        {
                            op: "add",
                            path: "/accessToken/claims/-",
                            value: {
                                name: "grantType",
                                value: grantType.toString()
                            }
                        }
                    ]
                };
            }
        } else {
            respBody = {
                "actionStatus": "SUCCESS",
                "operations": [
                    {
                        op: "add",
                        path: "/accessToken/claims/-",
                        value: {
                            name: "grantType",
                            value: grantType.toString()
                        }
                    },
                    {
                        op: "add",
                        path: "/accessToken/claims/-",
                        value: {
                            name: "isPermanent",
                            value: true
                        }
                    },
                    {
                        op: "add",
                        path: "/accessToken/claims/-",
                        value: {
                            name: "additionalRoles",
                            value: [
                                "accountant",
                                "manager"
                            ]
                        }
                    }
                ]
            };
        }
        OkInline_response_200 resp = {
            "body": respBody
        };
        log:printInfo("SUCCESS Response: " + resp.toString());
        return resp;   
    }   

    resource function post preIssueAccessTokenError(@http:Payload RequestBody payload) returns OkInline_response_200|BadRequestErrorResponse|InternalServerErrorErrorResponse {
        
        log:printInfo("Request Received to simulate an error");

        InternalServerErrorErrorResponse resp = {
            body: {
                actionStatus: "ERROR",
                errorMessage: "Internal server error",
                errorDescription: "Please try again"
            }
        };
        log:printInfo("ERROR Response: " + resp.toString());
        return resp; 
    }
}

// Function to get the email value from the claims
function getAccessTokenClaim(RequestBody requestPayload, string claimName) returns string? {
    
    AccessTokenClaims[] claims = requestPayload.event.accessToken.claims;
    foreach AccessTokenClaims claim in claims {
        if claim.name == claimName {
            return claim.name;
        }
    }
    return null;
}
