// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (9091, config = {host: "localhost"});

service / on ep0 {
    # handle pre-update password events
    #
    # + payload - parameter description 
    # + return - returns can be any of following types
    # OkInline_response_200 (Ok)
    # BadRequestErrorResponse (Bad Request)
    # InternalServerErrorErrorResponse (Server Error)
    resource function post preUpdatePassword(@http:Payload RequestBody payload) returns OkInline_response_200|BadRequestErrorResponse|InternalServerErrorErrorResponse {
        
        Event event = payload.event;
        log:printInfo("Pre Update Password Action request received: " + RequestBody.toString());

        if (event.user.updatingCredential is UnencryptedCredential) {
            UnencryptedCredential unencryptedCredential = <UnencryptedCredential>event.user.updatingCredential;
            string password = unencryptedCredential.value;
            return getResponse(password);
        } else {
            InternalServerErrorErrorResponse resp = { 
                body: { 
                    actionStatus: "ERROR", 
                    errorMessage: "Unable to decrypt the credential", 
                    errorDescription: "Please provide a unencrypted credential"
                } 
            };
            log:printInfo("ERROR Response: " + resp.toString());
            return resp;
        }
    }
}

function getResponse(string password) returns OkInline_response_200|BadRequestErrorResponse|InternalServerErrorErrorResponse {
    
    if (password == "myPassword@123") {
        InternalServerErrorErrorResponse resp = { 
            body: { 
                actionStatus: "ERROR", 
                errorMessage: "Internal server error", 
                errorDescription: "Please try again"
            } 
        };
        log:printInfo("ERROR Response: " + resp.toString());
        return resp;
    } else if (password == "myPassword@1234") {
        OkInline_response_200 resp = { 
            body: { 
                actionStatus: "FAILED", 
                failureReason: "Compromised password", 
                failureDescription: "Provide a different password"
            } 
        };
        log:printInfo("FAILED Response: " + resp.toString());
        return resp;
    } else {
        OkInline_response_200 resp = { body: { actionStatus: "SUCCESS" } };
        log:printInfo("SUCCESS Response: " + resp.toString());
        return resp;
    }
}
