// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type BadRequestErrorResponse record {|
    *http:BadRequest;
    ErrorResponse body;
|};

public type OkInline_response_200 record {|
    *http:Ok;
    Inline_response_200 body;
|};

public type InternalServerErrorErrorResponse record {|
    *http:InternalServerError;
    ErrorResponse body;
|};

# Defines the additional data related to the updating credential.
public type AdditionalData AdditionalDataForHashedPassword;

# Defines the success response.
public type SuccessResponse record {
    "SUCCESS" actionStatus;
};

# Contains information about the user associated with the password update request.
public type User record {
    # Defines the unique identifier of the user.
    string id;
    UnencryptedCredential|EncryptedCredential updatingCredential;
};

# Refers to the organization to which the user belongs. Organizations represent partners/enterprise customers in Business-to-Business (B2B) use cases.
public type Organization record {
    # The unique identifier of the organization.
    string id;
    # Name of the organization used to identify the organization in configurations, user interfaces, etc.
    string name;
};

# Represents an encrypted credential using JSON Web Encryption (JWE).
# 
# When a public key is configured for the pre-password update action, 
# the `updatingCredential` object is encrypted into a JWE string. 
# The payload of this JWE follows the structure of the `UnencryptedCredential` object.
# 
# Example JWE representation:
# ```
# eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZHQ00ifQ.OKOawDo13gRp2ojaHV7LFsQ.48V1_ALb6US04U3b.5eym8X3LNvUubV4Y0kH.XFBoMYUZodetZdvTiFvSkQ
# ```
# 
# Decrypted Payload Example (UnencryptedCredential structure):
# ```
# {
#   "type": "PASSWORD",
#   "format": "HASH",
#   "value": "cHRSHCjvmT",
#   "additionalData": {
#     "algorithm": "SHA256"
#   }
# }
# ```
# 
# This ensures secure transmission of the credential while allowing validation upon decryption.
public type EncryptedCredential string;

public type Inline_response_200 SuccessResponse|FailedResponse;

# When the external service responds with an ERROR state, it can return an HTTP status code of 400, 401, or 500, indicating either a validation failure or an issue processing the request. 
public type ErrorResponse record {
    # Indicates the outcome of the request. For an error operation, this should be set to ERROR.
    "ERROR" actionStatus;
    # The cause of the error.
    string errorMessage;
    # A detailed description of the error.
    string errorDescription;
};

# This property represents the tenant under which the token request is being processed.
public type Tenant record {
    # The unique numeric identifier of the tenant.
    string id;
    # The domain name of the tenant.
    string name;
};

# Indicates the user store in which the user's data is being managed.
public type UserStore record {
    # The unique identifier for the user store.
    string id;
    # User store name used to identify the user store in configuration settings, user interfaces, and administrative tasks.
    string name;
};

public type FailedResponse record {
    # Indicates the outcome of the request. For a failed operation, this should be set to FAILED.
    "FAILED" actionStatus;
    # Provides the reason for failing password update.
    string failureReason;
    # Offers a detailed explanation of the failure
    string failureDescription;
};

# Defines the context data related to the pre issue access token event that needs to be shared with the custom service to process and execute.
public type Event record {
    # This indicates whether the password update was initiated by an admin, a user, or an application.
    "USER"|"ADMIN"|"APPLICATION" initiatorType;
    # This indicates whether the password update was initiated over a password reset flow, update flow, or an invite flow.
    "RESET"|"UPDATE"|"INVITE" action;
    # This property represents the tenant under which the token request is being processed.
    Tenant tenant;
    # Contains information about the user associated with the password update request.
    User user;
    # Refers to the organization to which the user belongs. Organizations represent partners/enterprise customers in Business-to-Business (B2B) use cases.
    Organization organization?;
    # Indicates the user store in which the user's data is being managed.
    UserStore userStore;
};

# Defines additional data related to hashed passwords.
public type AdditionalDataForHashedPassword record {
    "SHA256" algorithm?;
};

public type UnencryptedCredential record {
    # Defines the credential type.
    "PASSWORD" 'type;
    # Defines the format the credential is shared.
    "PLAIN_TEXT"|"HASH" format;
    # Defines the value.
    string value;
    # Defines the additional data related to the updating credential.
    AdditionalData additionalData?;
};

public type RequestBody record {
    # A unique identifier that associates with the password updating flow in Asgardeo
    string flowId?;
    # A unique correlation identifier that associates with the password update request received by Asgardeo
    string requestId?;
    # Specifies the action being triggered, which in this case is PRE_UPDATE_PASSWORD.
    "PRE_UPDATE_PASSWORD" actionType;
    # Defines the context data related to the pre issue access token event that needs to be shared with the custom service to process and execute.
    Event event;
};
